//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timekeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timekeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonBold {
            get {
                object obj = ResourceManager.GetObject("buttonBold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCancel {
            get {
                object obj = ResourceManager.GetObject("buttonCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseStartGap {
            get {
                object obj = ResourceManager.GetObject("buttonCloseStartGap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseStopGap {
            get {
                object obj = ResourceManager.GetObject("buttonCloseStopGap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonFilter {
            get {
                object obj = ResourceManager.GetObject("buttonFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonFirst {
            get {
                object obj = ResourceManager.GetObject("buttonFirst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonGo {
            get {
                object obj = ResourceManager.GetObject("buttonGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonItalics {
            get {
                object obj = ResourceManager.GetObject("buttonItalics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonLast {
            get {
                object obj = ResourceManager.GetObject("buttonLast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonListBulleted {
            get {
                object obj = ResourceManager.GetObject("buttonListBulleted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonListNumbered {
            get {
                object obj = ResourceManager.GetObject("buttonListNumbered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonNew {
            get {
                object obj = ResourceManager.GetObject("buttonNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonNext {
            get {
                object obj = ResourceManager.GetObject("buttonNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPrev {
            get {
                object obj = ResourceManager.GetObject("buttonPrev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPrinter {
            get {
                object obj = ResourceManager.GetObject("buttonPrinter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRefresh {
            get {
                object obj = ResourceManager.GetObject("buttonRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRevert {
            get {
                object obj = ResourceManager.GetObject("buttonRevert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonStop {
            get {
                object obj = ResourceManager.GetObject("buttonStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonStrikethrough {
            get {
                object obj = ResourceManager.GetObject("buttonStrikethrough", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUnderlined {
            get {
                object obj = ResourceManager.GetObject("buttonUnderlined", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUnlock {
            get {
                object obj = ResourceManager.GetObject("buttonUnlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconFolderSmall {
            get {
                object obj = ResourceManager.GetObject("iconFolderSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconProject {
            get {
                object obj = ResourceManager.GetObject("iconProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconTask {
            get {
                object obj = ResourceManager.GetObject("iconTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body, table {{
        ///    font-family: {0}, Tahoma, Verdana, Arial, Helv, sans-serif;
        ///    margin: 1em;
        ///    font-size: {1}pt;
        ///    border-collapse: collapse;
        ///    empty-cells: show;
        ///}}
        ///.memo {{
        ///    margin-left: 2em;
        ///}}.
        /// </summary>
        internal static string ReportCssTemplate {
            get {
                return ResourceManager.GetString("ReportCssTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{0}&lt;/title&gt;
        ///  &lt;style&gt;
        ///    {1}
        ///  &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  {2}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE tasks (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tasks (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    timestamp_c
        ///) VALUES (
        ///    &apos;Default Task&apos;,
        ///    &apos;Right click this task and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE timekeeper (
        ///    id integer primary key,
        ///    task_id integer,
        ///    project_id integer,
        ///    timestamp_s datetime,
        ///    timestamp_e datetime,
        ///    seconds integer,
        ///    pre_log varchar,
        ///    post_log varchar,
        ///    is_locked bool
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meta (
        ///    key string,
        ///    value string,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;version&apos;,
        ///    &apos;2.0.0.0&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE projects (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO projects (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    timestamp_c
        ///) VALUES (
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click this project and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE tasks (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    project_id__last int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///).
        /// </summary>
        internal static string SQL_2100_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tasks (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    project_id__last,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Task&apos;,
        ///    &apos;Right click this task and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE journal (
        ///    id integer primary key,
        ///    timestamp_entry datetime,
        ///    description varchar,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE grid_views (
        ///    id integer primary key,
        ///    name varchar,
        ///    description varchar,
        ///    sort_index int,
        ///    task_list varchar,
        ///    project_list varchar,
        ///    date_preset int,
        ///    start_date varchar,
        ///    end_date varchar,
        ///    group_by int,
        ///    data_from int,
        ///    hide_empty_rows int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime,
        ///    end_date_type int
        ///).
        /// </summary>
        internal static string SQL_2100_GridViews_Create {
            get {
                return ResourceManager.GetString("SQL_2100_GridViews_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE timekeeper (
        ///    id integer primary key,
        ///    task_id integer,
        ///    project_id integer,
        ///    timestamp_s datetime,
        ///    timestamp_e datetime,
        ///    seconds integer,
        ///    pre_log varchar,
        ///    post_log varchar,
        ///    is_locked bool
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meta (
        ///    key string,
        ///    value string,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;created&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;version&apos;,
        ///    &apos;2.1.0.0&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;id&apos;,
        ///    &apos;{1}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///.
        /// </summary>
        internal static string SQL_2100_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE projects (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO projects (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click this project and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE tasks (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder boolean,
        ///    is_hidden boolean,
        ///    is_deleted boolean,
        ///    project_id__last int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tasks (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_hidden,
        ///    is_deleted,
        ///    project_id__last,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Task&apos;,
        ///    &apos;Right click this task and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE journal (
        ///    id integer primary key,
        ///    timestamp_entry datetime,
        ///    description varchar,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE grid_views (
        ///    id integer primary key,
        ///    name varchar,
        ///    description varchar,
        ///    sort_index int,
        ///    task_list varchar,
        ///    project_list varchar,
        ///    date_preset int,
        ///    start_date varchar,
        ///    end_date varchar,
        ///    end_date_type int,
        ///    group_by int,
        ///    data_from int,
        ///    hide_empty_rows int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_GridViews_Create {
            get {
                return ResourceManager.GetString("SQL_2204_GridViews_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE timekeeper (
        ///    id integer primary key,
        ///    task_id integer,
        ///    project_id integer,
        ///    timestamp_s datetime,
        ///    timestamp_e datetime,
        ///    seconds integer,
        ///    pre_log varchar,
        ///    post_log varchar,
        ///    is_locked boolean
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meta (
        ///    key string,
        ///    value string,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;created&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;version&apos;,
        ///    &apos;2.2.0.4&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;id&apos;,
        ///    &apos;{1}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///.
        /// </summary>
        internal static string SQL_2204_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE projects (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder boolean,
        ///    is_hidden boolean,
        ///    is_deleted boolean,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO projects (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_hidden,
        ///    is_deleted,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click this project and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Activity
        ///(
        ///    ActivityId      INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime      DATETIME NOT NULL,
        ///    ModifyTime      DATETIME NOT NULL,
        ///    ActivityGuid    TEXT NOT NULL,
        ///    Name            TEXT NOT NULL,
        ///    Description     TEXT,
        ///    ParentId        INTEGER,
        ///    SortOrderNo     INTEGER,
        ///    LastProjectId   INTEGER,
        ///    IsFolder        BOOLEAN NOT NULL,
        ///    IsOpened        BOOLEAN NOT NULL,
        ///    IsHidden        BOOLEAN NOT NULL,
        ///    IsDeleted       BOOLEAN NOT NULL,
        ///    H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Activity
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    ActivityGuid,
        ///
        ///    Name,
        ///    Description,
        ///    ParentId,
        ///
        ///    SortOrderNo,
        ///    LastProjectId,
        ///
        ///    IsFolder,
        ///    IsOpened,
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Default Activity&apos;,
        ///    &apos;Right click and select Edit to change the name or this description&apos;,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null
        ///)
        ///.
        /// </summary>
        internal static string SQL_3000_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Category
        ///(
        ///    CategoryId      INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime      DATETIME    NOT NULL,
        ///    ModifyTime      DATETIME    NOT NULL,
        ///    CategoryGuid    TEXT        NOT NULL,
        ///    Name            TEXT        NOT NULL,
        ///    Description     TEXT            NULL,
        ///    SortOrderNo     INTEGER     NOT NULL,
        ///    IsHidden        BOOLEAN     NOT NULL,
        ///    IsDeleted       BOOLEAN     NOT NULL,
        ///    HiddenTime      DATETIME        NULL,
        ///    DeletedTime     DATETIME   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Category_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Category_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Category
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    CategoryGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Follow Up&apos;,
        ///    &apos;Follow Up on this Journal Entry&apos;,
        ///    
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null
        ///);
        ///
        ///INSERT INTO Category
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    CategoryGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Category_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Category_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Diary
        ///(
        ///    DiaryEntryId        INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime          DATETIME NOT NULL,
        ///    ModifyTime          DATETIME NOT NULL,
        ///    DiaryEntryGuid      TEXT NOT NULL,
        ///    EntryTime           DATETIME NOT NULL,
        ///    Memo                TEXT NOT NULL,
        ///    LocationId          INTEGER,
        ///    CategoryId          INTEGER
        ///);
        ///
        ///CREATE UNIQUE INDEX idx_Diary_DiaryEntryId  ON Diary (DiaryEntryId);
        ///CREATE UNIQUE INDEX idx_Diary_EntryTime     ON Diary (EntryTime);
        ///.
        /// </summary>
        internal static string SQL_3000_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE FilterOptions
        ///(
        ///    FilterOptionsId             INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime                  DATETIME NOT NULL,
        ///    ModifyTime                  DATETIME NOT NULL,
        ///
        ///    Name                        TEXT,
        ///    Description                 TEXT,
        ///    SortOrderNo                 INTEGER,
        ///    ActivityList                TEXT,
        ///    ProjectList                 TEXT,
        ///    SystemDatePresetId          INTEGER,
        ///    FromDate                    DATETIME,
        ///    ToDate               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_FilterOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3000_FilterOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE GridOptions
        ///(
        ///    GridOptionsId               INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime                  DATETIME NOT NULL,
        ///    ModifyTime                  DATETIME NOT NULL,
        ///    Name                        TEXT NOT NULL,
        ///    Description                 TEXT,
        ///    SortOrderNo                 INTEGER,
        ///    ActivityFilter              TEXT,
        ///    ProjectFilter               TEXT,
        ///    SystemDatePresetId          INTEGER,
        ///    FromDate                    DATETIME,
        ///    ToDate          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_GridOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3000_GridOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Journal
        ///(
        ///    JournalEntryId      INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime          DATETIME NOT NULL,
        ///    ModifyTime          DATETIME NOT NULL,
        ///    JournalEntryGuid    TEXT NOT NULL,
        ///    ExternalEntryId     INTEGER,
        ///    ActivityId          INTEGER NOT NULL,
        ///    ProjectId           INTEGER NOT NULL,
        ///    StartTime           DATETIME,
        ///    StopTime            DATETIME,
        ///    Seconds             INTEGER NOT NULL,
        ///    Memo                TEXT,
        ///    LocationId          INTEGER,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Location
        ///(
        ///    LocationId      INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime      DATETIME    NOT NULL,
        ///    ModifyTime      DATETIME    NOT NULL,
        ///    LocationGuid    TEXT        NOT NULL,
        ///    Name            TEXT        NOT NULL,
        ///    Description     TEXT            NULL,
        ///    SortOrderNo     INTEGER     NOT NULL,
        ///    IsHidden        BOOLEAN     NOT NULL,
        ///    IsDeleted       BOOLEAN     NOT NULL,
        ///    HiddenTime      DATETIME        NULL,
        ///    DeletedTime     DATETIME   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Location_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Location_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Location
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    LocationGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Work&apos;,
        ///    &apos;Entry Created at Work&apos;,
        ///    
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null
        ///);
        ///
        ///INSERT INTO Location
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    LocationGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    IsHidden,
        ///    Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Location_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Location_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300
        ///(
        ///    MetaId	INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    Key         TEXT NOT NULL,
        ///    Value       TEXT NOT NULL
        ///);
        ///.
        /// </summary>
        internal static string SQL_3000_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Created&apos;, &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Upgraded&apos;, &apos;0001-01-01 00:00:00&apos;
        ///);
        ///
        ///INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Version&apos;, &apos;3.0.0.0&apos;
        ///);
        ///
        ///INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Id&apos;, &apos;{1}&apos;
        ///);
        ///.
        /// </summary>
        internal static string SQL_3000_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Options
        ///(
        ///    OptionsId       INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime      DATETIME NOT NULL,
        ///    ModifyTime      DATETIME NOT NULL,
        ///    Key             TEXT NOT NULL,
        ///    Value           TEXT NOT NULL
        ///);
        ///.
        /// </summary>
        internal static string SQL_3000_Options_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Options_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Options
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    Key,
        ///    Value
        ///
        ///) VALUES (
        ///    datetime(&apos;now&apos;),
        ///    datetime(&apos;now&apos;),
        ///    &apos;LastActivity&apos;,
        ///    null
        ///);
        ///
        ///INSERT INTO Options
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    Key,
        ///    Value
        ///
        ///) VALUES (
        ///    datetime(&apos;now&apos;),
        ///    datetime(&apos;now&apos;),
        ///    &apos;LastProject&apos;,
        ///    null
        ///);
        ///
        ///INSERT INTO Options
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    Key,
        ///    Value
        ///
        ///) VALUES (
        ///    datetime(&apos;now&apos;),
        ///    datetime(&apos;now&apos;),
        ///    &apos;LastGridView&apos;,
        ///    nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Options_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Options_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Project (
        ///    ProjectId       INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime      DATETIME NOT NULL,
        ///    ModifyTime      DATETIME NOT NULL,
        ///    ProjectGuid     TEXT NOT NULL,
        ///    Name            TEXT NOT NULL,
        ///    Description     TEXT,
        ///    ParentId        INTEGER,
        ///    SortOrderNo     INTEGER,
        ///    LastActivityId  INTEGER,
        ///    IsFolder        BOOLEAN NOT NULL,
        ///    IsOpened        BOOLEAN NOT NULL,
        ///    IsHidden        BOOLEAN NOT NULL,
        ///    IsDeleted       BOOLEAN NOT NULL,
        ///    Hid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3000_Project_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Project
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    ProjectGuid,
        ///
        ///    Name,
        ///    Description,
        ///    ParentId,
        ///
        ///    SortOrderNo,
        ///    LastActivityId,
        ///
        ///    IsFolder,
        ///    IsOpened,
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click and select Edit to change the name or this description&apos;,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null
        ///)
        ///.
        /// </summary>
        internal static string SQL_3000_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE ReportOptions
        ///(
        ///    ReportOptionsId     INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime          DATETIME NOT NULL,
        ///    ModifyTime          DATETIME NOT NULL,
        ///    Name                TEXT NOT NULL,
        ///    Description         TEXT,
        ///    FilterOptionsId     INTEGER,
        ///    SortBy1             INTEGER,
        ///    SortBy2             INTEGER,
        ///    SortBy3             INTEGER
        ///);
        ///.
        /// </summary>
        internal static string SQL_3000_ReportOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3000_ReportOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE SystemDatePreset
        ///(
        ///    SystemDatePresetId          INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime                  DATETIME NOT NULL,
        ///    ModifyTime                  DATETIME NOT NULL,
        ///    Name                        TEXT NOT NULL,
        ///    Description                 TEXT
        ///);
        ///.
        /// </summary>
        internal static string SQL_3000_SystemDatePreset_Create {
            get {
                return ResourceManager.GetString("SQL_3000_SystemDatePreset_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE SystemGridGroupBy
        ///(
        ///    SystemGridGroupById         INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime                  DATETIME NOT NULL,
        ///    ModifyTime                  DATETIME NOT NULL,
        ///    Name                        TEXT NOT NULL,
        ///    Description                 TEXT
        ///);
        ///.
        /// </summary>
        internal static string SQL_3000_SystemGridGroupBy_Create {
            get {
                return ResourceManager.GetString("SQL_3000_SystemGridGroupBy_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE SystemGridTimeDisplay
        ///(
        ///    SystemGridTimeDisplayId     INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime                  DATETIME NOT NULL,
        ///    ModifyTime                  DATETIME NOT NULL,
        ///    Name                        TEXT NOT NULL,
        ///    Description                 TEXT
        ///);
        ///.
        /// </summary>
        internal static string SQL_3000_SystemGridTimeDisplay_Create {
            get {
                return ResourceManager.GetString("SQL_3000_SystemGridTimeDisplay_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timekeeper256 {
            get {
                object obj = ResourceManager.GetObject("timekeeper256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timekeeper48 {
            get {
                object obj = ResourceManager.GetObject("timekeeper48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
