//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timekeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timekeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonBold {
            get {
                object obj = ResourceManager.GetObject("buttonBold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCancel {
            get {
                object obj = ResourceManager.GetObject("buttonCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseStartGap {
            get {
                object obj = ResourceManager.GetObject("buttonCloseStartGap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseStopGap {
            get {
                object obj = ResourceManager.GetObject("buttonCloseStopGap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonFilter {
            get {
                object obj = ResourceManager.GetObject("buttonFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonFirst {
            get {
                object obj = ResourceManager.GetObject("buttonFirst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonGo {
            get {
                object obj = ResourceManager.GetObject("buttonGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonItalics {
            get {
                object obj = ResourceManager.GetObject("buttonItalics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonLast {
            get {
                object obj = ResourceManager.GetObject("buttonLast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonListBulleted {
            get {
                object obj = ResourceManager.GetObject("buttonListBulleted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonListNumbered {
            get {
                object obj = ResourceManager.GetObject("buttonListNumbered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonNew {
            get {
                object obj = ResourceManager.GetObject("buttonNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonNext {
            get {
                object obj = ResourceManager.GetObject("buttonNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPrev {
            get {
                object obj = ResourceManager.GetObject("buttonPrev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPrinter {
            get {
                object obj = ResourceManager.GetObject("buttonPrinter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRefresh {
            get {
                object obj = ResourceManager.GetObject("buttonRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRevert {
            get {
                object obj = ResourceManager.GetObject("buttonRevert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonStop {
            get {
                object obj = ResourceManager.GetObject("buttonStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonStrikethrough {
            get {
                object obj = ResourceManager.GetObject("buttonStrikethrough", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUnderlined {
            get {
                object obj = ResourceManager.GetObject("buttonUnderlined", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUnlock {
            get {
                object obj = ResourceManager.GetObject("buttonUnlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconFolderSmall {
            get {
                object obj = ResourceManager.GetObject("iconFolderSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconProject {
            get {
                object obj = ResourceManager.GetObject("iconProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconTask {
            get {
                object obj = ResourceManager.GetObject("iconTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body, table {{
        ///    font-family: {0}, Tahoma, Verdana, Arial, Helv, sans-serif;
        ///    margin: 1em;
        ///    font-size: {1}pt;
        ///    border-collapse: collapse;
        ///    empty-cells: show;
        ///}}
        ///.memo {{
        ///    margin-left: 2em;
        ///}}.
        /// </summary>
        internal static string ReportCssTemplate {
            get {
                return ResourceManager.GetString("ReportCssTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{0}&lt;/title&gt;
        ///  &lt;style&gt;
        ///    {1}
        ///  &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  {2}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE tasks (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tasks (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    timestamp_c
        ///) VALUES (
        ///    &apos;Default Task&apos;,
        ///    &apos;Right click this task and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE timekeeper (
        ///    id integer primary key,
        ///    task_id integer,
        ///    project_id integer,
        ///    timestamp_s datetime,
        ///    timestamp_e datetime,
        ///    seconds integer,
        ///    pre_log varchar,
        ///    post_log varchar,
        ///    is_locked bool
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meta (
        ///    key string,
        ///    value string,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;version&apos;,
        ///    &apos;2.0.0.0&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE projects (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO projects (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    timestamp_c
        ///) VALUES (
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click this project and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2000_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE tasks (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    project_id__last int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///).
        /// </summary>
        internal static string SQL_2100_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tasks (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    project_id__last,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Task&apos;,
        ///    &apos;Right click this task and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE journal (
        ///    id integer primary key,
        ///    timestamp_entry datetime,
        ///    description varchar,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE grid_views (
        ///    id integer primary key,
        ///    name varchar,
        ///    description varchar,
        ///    sort_index int,
        ///    task_list varchar,
        ///    project_list varchar,
        ///    date_preset int,
        ///    start_date varchar,
        ///    end_date varchar,
        ///    group_by int,
        ///    data_from int,
        ///    hide_empty_rows int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime,
        ///    end_date_type int
        ///).
        /// </summary>
        internal static string SQL_2100_GridOptions_Create {
            get {
                return ResourceManager.GetString("SQL_2100_GridOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE timekeeper (
        ///    id integer primary key,
        ///    task_id integer,
        ///    project_id integer,
        ///    timestamp_s datetime,
        ///    timestamp_e datetime,
        ///    seconds integer,
        ///    pre_log varchar,
        ///    post_log varchar,
        ///    is_locked bool
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meta (
        ///    key string,
        ///    value string,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;created&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;version&apos;,
        ///    &apos;2.1.0.0&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;id&apos;,
        ///    &apos;{1}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///.
        /// </summary>
        internal static string SQL_2100_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE projects (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder bool,
        ///    is_deleted bool,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO projects (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_deleted,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click this project and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2100_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE tasks (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder boolean,
        ///    is_hidden boolean,
        ///    is_deleted boolean,
        ///    project_id__last int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tasks (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_hidden,
        ///    is_deleted,
        ///    project_id__last,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Task&apos;,
        ///    &apos;Right click this task and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE journal (
        ///    id integer primary key,
        ///    timestamp_entry datetime,
        ///    description varchar,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE grid_views (
        ///    id integer primary key,
        ///    name varchar,
        ///    description varchar,
        ///    sort_index int,
        ///    task_list varchar,
        ///    project_list varchar,
        ///    date_preset int,
        ///    start_date varchar,
        ///    end_date varchar,
        ///    end_date_type int,
        ///    group_by int,
        ///    data_from int,
        ///    hide_empty_rows int,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_GridOptions_Create {
            get {
                return ResourceManager.GetString("SQL_2204_GridOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE timekeeper (
        ///    id integer primary key,
        ///    task_id integer,
        ///    project_id integer,
        ///    timestamp_s datetime,
        ///    timestamp_e datetime,
        ///    seconds integer,
        ///    pre_log varchar,
        ///    post_log varchar,
        ///    is_locked boolean
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE meta (
        ///    key string,
        ///    value string,
        ///    timestamp_c datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;created&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;version&apos;,
        ///    &apos;2.2.0.4&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO meta (
        ///    key, value, timestamp_c
        ///) VALUES (
        ///    &apos;id&apos;,
        ///    &apos;{1}&apos;,
        ///    &apos;{0}&apos;
        ///);
        ///.
        /// </summary>
        internal static string SQL_2204_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE projects (
        ///    id integer primary key,
        ///    name string,
        ///    descr string,
        ///    parent_id integer,
        ///    is_folder boolean,
        ///    is_hidden boolean,
        ///    is_deleted boolean,
        ///    timestamp_c datetime,
        ///    timestamp_m datetime
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO projects (
        ///    name,
        ///    descr,
        ///    parent_id,
        ///    is_folder,
        ///    is_hidden,
        ///    is_deleted,
        ///    timestamp_c,
        ///    timestamp_m
        ///) VALUES (
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click this project and select Edit to change the name or this description&apos;,
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;
        ///)
        ///.
        /// </summary>
        internal static string SQL_2204_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: Activity
        ///-- Purpose: An Activity is one of the two primary dimensions to time-
        ///--          tracking. The other is Project. Activity can be generally
        ///--          thought of as the verbs: as in what are you DOING and not
        ///--          what are you DELIVERING.
        ///-- Added..: Timekeeper 2.0
        ///-- Updated: Timekeeper 3.0
        ///-- AKA....: This table was known as &apos;tasks&apos; prior to Timekeeper 3.0
        ///---------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Activity
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    ActivityGuid,
        ///
        ///    Name,
        ///    Description,
        ///    ParentId,
        ///
        ///    SortOrderNo,
        ///    LastProjectId,
        ///
        ///    IsFolder,
        ///    IsFolderOpened,
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Default Activity&apos;,
        ///    &apos;Right click and select Edit to change the name or this description&apos;,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_3001_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: Category
        ///-- Purpose: Provide a method for categorizing, tagging, or otherwise
        ///--          flagging a row with a piece of additional, user-defined
        ///--          information. For example, &quot;follow up&quot;, &quot;important&quot;, etc.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE Category
        ///(
        ///    CategoryId          INTEGER     NOT NULL PRIM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Category_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Category_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Category
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    CategoryGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Follow Up&apos;,
        ///    &apos;Follow Up on this Journal Entry&apos;,
        ///    
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null
        ///);
        ///
        ///INSERT INTO Category
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    CategoryGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Category_Insert {
            get {
                return ResourceManager.GetString("SQL_3001_Category_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: Diary
        ///-- Purpose: A Diary entry is a special Timekeeper journal entry, one
        ///--          not tied to particular time period or range but to a single
        ///--          point in time (a specific day, hour, or minute, but most
        ///--          typically a day).
        ///-- Added..: Timekeeper 2.1
        ///-- Updated: Timekeeper 3.0
        ///-- AKA....: This table was known as &apos;journal&apos; prior to Timekeeper 3.0
        ///------------------------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: FilterOptions
        ///-- Purpose: This table stores standard filtering options for various
        ///--          user reporting and querying tasks. If a particular form or
        ///--          feature of Timekeeper requires filtering, this row is first
        ///--          populated, then attached to the specific instance of user
        ///--          filtering. For example, both the Report and Grid forms
        ///--          support filtering, but each of these also has [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_FilterOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3001_FilterOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: GridOptions
        ///-- Purpose: This table stores user options for saving a particular view
        ///--          of the Grid display.
        ///-- Added..: Timekeeper 2.1
        ///-- Updated: Timekeeper 3.0
        ///-- AKA....: This table was known as &apos;grid_views&apos; prior to Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE GridOptions
        ///(
        ///    GridOptionsId       INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_GridOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3001_GridOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: Journal
        ///-- Purpose: This is the primary Timekeeper Journal Entry table and the
        ///--          entire reason this whole project exists. As the user starts
        ///--          and stops the timer, rows are created and updated here.
        ///-- Added..: Timekeeper 2.0
        ///-- Updated: Timekeeper 3.0
        ///-- AKA....: This table was known as &apos;timekeeper&apos; prior to Timekeeper 3.0
        ///------------------------------------------------------------------------        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: Location
        ///-- Purpose: Provide a method for tagging Timekeeper data with a specific
        ///--          geographic location as well as a time zone. The time zone
        ///--          data, combined with row timestamps can be used to determine
        ///--          whether a particular entry was recorded with DST or not.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Location_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Location_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Location
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    LocationGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Work&apos;,
        ///    &apos;Entry Created at Work&apos;,
        ///    
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null
        ///);
        ///
        ///INSERT INTO Location
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    LocationGuid,
        ///
        ///    Name,
        ///    Description,
        ///
        ///    SortOrderNo,
        ///
        ///    IsHidden,
        ///    Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Location_Insert {
            get {
                return ResourceManager.GetString("SQL_3001_Location_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300
        ///-- Purpose: This is the table containing meta information about the
        ///--          database. It also serves as a unique identifier to help
        ///--          immediately distinguish a Timekeeper database from any
        ///--          other SQLite database. It contains the database&apos;s create
        ///--          date, update date, UUID, and schema version.
        ///-- Added..: Timekeeper 2.0
        ///-- Updated: Timekeeper 3.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Created&apos;, &apos;{0}&apos;
        ///);
        ///
        ///INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Upgraded&apos;, &apos;0001-01-01 00:00:00&apos;
        ///);
        ///
        ///INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Version&apos;, &apos;{3}&apos;
        ///);
        ///
        ///INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 (
        ///    Key, Value
        ///) VALUES (
        ///    &apos;Id&apos;, &apos;{1}&apos;
        ///);
        ///.
        /// </summary>
        internal static string SQL_3001_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_3001_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: Options
        ///-- Purpose: Most user options are stored in the Windows Registry.
        ///--          However, some options do not apply system-wide and are
        ///--          specific to the opened database. Those options go here.
        ///--          Items like tracking the last-timed Activity or the last
        ///--          used Report view.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///--------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Options_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Options_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Options
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    Key,
        ///    Value
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;LastActivity&apos;,
        ///    null
        ///);
        ///
        ///INSERT INTO Options
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    Key,
        ///    Value
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;LastProject&apos;,
        ///    null
        ///);
        ///
        ///INSERT INTO Options
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    Key,
        ///    Value
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;LastGridView&apos;,
        ///    null
        ///);
        ///
        ///INSERT INTO Options
        ///(
        ///    CreateTime,
        ///    Modify [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Options_Insert {
            get {
                return ResourceManager.GetString("SQL_3001_Options_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: Project
        ///-- Purpose: A Project is one of the two primary dimensions to time-
        ///--          tracking. The other is Activity. Project can be generally
        ///--          thought of as the nouns: as in what are you DELIVERING and
        ///--          not what are you DOING.
        ///-- Added..: Timekeeper 2.0
        ///-- Updated: Timekeeper 3.0
        ///-- AKA....: This table was known as &apos;projects&apos; prior to Timekeeper 3.0
        ///---------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Project_Create {
            get {
                return ResourceManager.GetString("SQL_3001_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Project
        ///(
        ///    CreateTime,
        ///    ModifyTime,
        ///    ProjectGuid,
        ///
        ///    Name,
        ///    Description,
        ///    ParentId,
        ///
        ///    SortOrderNo,
        ///    LastActivityId,
        ///
        ///    IsFolder,
        ///    IsFolderOpened,
        ///    IsHidden,
        ///    IsDeleted,
        ///    HiddenTime,
        ///    DeletedTime
        ///
        ///) VALUES (
        ///    &apos;{0}&apos;,
        ///    &apos;{0}&apos;,
        ///    &apos;{1}&apos;,
        ///
        ///    &apos;Default Project&apos;,
        ///    &apos;Right click and select Edit to change the name or this description&apos;,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    
        ///    0,
        ///    0,
        ///    0,
        ///    0,
        ///    
        ///    null,
        ///    null
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_3001_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: RefDatePreset
        ///-- Purpose: The data filtering interface uses a drop-down selection of
        ///--          date presets for quick date-range selection. For example,
        ///--          Today, Last Week, This Month, Last Year, and so on. Those
        ///--          values are stored here.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE RefDatePreset
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_RefDatePreset_Create {
            get {
                return ResourceManager.GetString("SQL_3001_RefDatePreset_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: RefGroupBy
        ///-- Purpose: The data filtering interface uses a drop-down selection of
        ///--          date &quot;Group By&quot; values. For example, Week, Month, Year.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE RefGroupBy
        ///(
        ///    RefGroupById    INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime          DATETIME    NOT NULL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_RefGroupBy_Create {
            get {
                return ResourceManager.GetString("SQL_3001_RefGroupBy_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: RefItemType
        ///-- Purpose: Assigns identifiers to &quot;Activity&quot; and &quot;Project&quot;.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE RefItemType
        ///(
        ///    RefItemTypeId       INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///    CreateTime          DATETIME    NOT NULL,
        ///    ModifyTime          DATETIME    NOT NULL,
        ///    Name                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_RefItemType_Create {
            get {
                return ResourceManager.GetString("SQL_3001_RefItemType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: RefTimeDisplay
        ///-- Purpose: The interface uses a drop-down selection of time display
        ///--          formats to control how sum(Journal.Seconds) is displayed.
        ///--          For example, hh:mm:ss, Hours, Minutes, Seconds.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE RefTimeDisplay
        ///(
        ///    RefTimeDisplayId    INTEGER     NOT NULL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_RefTimeDisplay_Create {
            get {
                return ResourceManager.GetString("SQL_3001_RefTimeDisplay_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: RefTimeZone
        ///-- Purpose: Map Windows&apos; time zones to a unique, interinal identifier
        ///--          better suited for use as foreign key constraints.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE RefTimeZone
        ///(
        ///    RefTimeZoneId       INTEGER     NOT NULL PRIMARY KEY,
        ///    OSTimeZone          TEXT        NOT NULL
        ///);
        ///
        ///CREATE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_RefTimeZone_Create {
            get {
                return ResourceManager.GetString("SQL_3001_RefTimeZone_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------
        ///-- Table..: ReportOptions
        ///-- Purpose: This table stores user options for saving a particular view
        ///--          of the Report window.
        ///-- Added..: Timekeeper 3.0
        ///-- Updated: Timekeeper 3.0
        ///------------------------------------------------------------------------
        ///
        ///CREATE TABLE ReportOptions
        ///(
        ///    ReportOptionsId     INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///
        ///    CreateTime          DATETIME    NOT NULL,
        ///    ModifyTime     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_3001_ReportOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3001_ReportOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timekeeper256 {
            get {
                object obj = ResourceManager.GetObject("timekeeper256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timekeeper48 {
            get {
                object obj = ResourceManager.GetObject("timekeeper48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
