//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timekeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timekeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonBold {
            get {
                object obj = ResourceManager.GetObject("buttonBold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCancel {
            get {
                object obj = ResourceManager.GetObject("buttonCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseStartGap {
            get {
                object obj = ResourceManager.GetObject("buttonCloseStartGap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCloseStopGap {
            get {
                object obj = ResourceManager.GetObject("buttonCloseStopGap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonFilter {
            get {
                object obj = ResourceManager.GetObject("buttonFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonFirst {
            get {
                object obj = ResourceManager.GetObject("buttonFirst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonGo {
            get {
                object obj = ResourceManager.GetObject("buttonGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonItalics {
            get {
                object obj = ResourceManager.GetObject("buttonItalics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonLast {
            get {
                object obj = ResourceManager.GetObject("buttonLast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonListBulleted {
            get {
                object obj = ResourceManager.GetObject("buttonListBulleted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonListNumbered {
            get {
                object obj = ResourceManager.GetObject("buttonListNumbered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonNew {
            get {
                object obj = ResourceManager.GetObject("buttonNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonNext {
            get {
                object obj = ResourceManager.GetObject("buttonNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPrev {
            get {
                object obj = ResourceManager.GetObject("buttonPrev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPrinter {
            get {
                object obj = ResourceManager.GetObject("buttonPrinter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRefresh {
            get {
                object obj = ResourceManager.GetObject("buttonRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRevert {
            get {
                object obj = ResourceManager.GetObject("buttonRevert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonStop {
            get {
                object obj = ResourceManager.GetObject("buttonStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonStrikethrough {
            get {
                object obj = ResourceManager.GetObject("buttonStrikethrough", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUnderlined {
            get {
                object obj = ResourceManager.GetObject("buttonUnderlined", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUnlock {
            get {
                object obj = ResourceManager.GetObject("buttonUnlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconFolderSmall {
            get {
                object obj = ResourceManager.GetObject("iconFolderSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconProject {
            get {
                object obj = ResourceManager.GetObject("iconProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconTask {
            get {
                object obj = ResourceManager.GetObject("iconTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string
        /// </summary>
        internal static string ReportCssTemplate {
            get {
                return ResourceManager.GetString("ReportCssTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string 
        /// </summary>
        internal static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2000_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2000_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2000_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2000_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2000_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2000_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2000_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2000_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2000_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2100_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2100_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2100_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2100_GridViews_Create {
            get {
                return ResourceManager.GetString("SQL_2100_GridViews_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2100_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2100_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2100_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2100_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2100_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2100_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2100_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2204_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2204_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2204_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2204_GridViews_Create {
            get {
                return ResourceManager.GetString("SQL_2204_GridViews_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2204_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2204_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2204_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_2204_Project_Create {
            get {
                return ResourceManager.GetString("SQL_2204_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_2204_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_2204_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_Activity_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Activity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_3000_Activity_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Activity_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_Category_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Category_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_3000_Category_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Category_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_Diary_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Diary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_FilterOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3000_FilterOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_GridOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3000_GridOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_Journal_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Journal_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_Location_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Location_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_3000_Location_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Location_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_Meta_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Meta_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO AA9FFC4E_5CEB_4E3F_83FE_7EC5D1A33300 TableName
        /// </summary>
        internal static string SQL_3000_Meta_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Meta_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_Options_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Options_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_3000_Options_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Options_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Project TableName
        /// </summary>
        internal static string SQL_3000_Project_Create {
            get {
                return ResourceManager.GetString("SQL_3000_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TableName
        /// </summary>
        internal static string SQL_3000_Project_Insert {
            get {
                return ResourceManager.GetString("SQL_3000_Project_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_ReportOptions_Create {
            get {
                return ResourceManager.GetString("SQL_3000_ReportOptions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_RefDatePreset_Create {
            get {
                return ResourceManager.GetString("SQL_3000_RefDatePreset_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_RefGridGroupBy_Create {
            get {
                return ResourceManager.GetString("SQL_3000_RefGridGroupBy_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TableName
        /// </summary>
        internal static string SQL_3000_RefGridTimeDisplay_Create {
            get {
                return ResourceManager.GetString("SQL_3000_RefGridTimeDisplay_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timekeeper256 {
            get {
                object obj = ResourceManager.GetObject("timekeeper256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timekeeper48 {
            get {
                object obj = ResourceManager.GetObject("timekeeper48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
